### ISSUE TITLE
Socket error when upload a file

### ISSUE THREAD

**Issue by eseceve** [tonistiigi/mega#2]
``` bash
mega-master: node example/upload [my_email] [my_pass] readme.md
Uploading [=================================================] 100% 0.0s
Uploaded readme.md 5220B
Download from: https://mega.co.nz/[...]
mega-master:  ls
example           lib               node_modules      package.json      pan_con_queso.txt readme.md         test
mega-master:  node example/upload [my_email] [my_pass] pan_con_queso.txt 
Uploading [-------------------------------------------------] 0% NaNs
/Users/eseceve/Downloads/mega-master/example/upload.js:27
    if (err) throw err
                   ^
Error: socket hang up
    at createHangUpError (http.js:1253:15)
    at Socket.socketOnEnd [as onend] (http.js:1341:23)
    at TCP.onread (net.js:419:26)
```

**Comment by tonistiigi** [comment]
So you get this error every time for this specific file? Or is this just a random error with no proper error handling?

If its the first case can you give me the bytesize of the file `pan_con_queso.txt`

**Comment by eseceve** [comment]
every time for this and others files.

```
-rwxr-xr-x@  1 eseceve  staff   597 Feb 13 10:45 package.json
-rwxrwxrwx   1 eseceve  staff     5 Feb 15 14:27 pan_con_queso.txt
-rwxr-xr-x@  1 eseceve  staff  5220 Feb 13 10:45 readme.md
```

**Comment by tonistiigi** [comment]
Thanks. Got the error myself for this file size. Seems my new faster implementation for CRC-MAC was not quite correct. I'll work on it later today. `v0.0.6` seems to be working correctly.

**Comment by tonistiigi** [comment]
I think this only happened on files smaller than 16B and one other very rare case. Please reopen if you still catch this.

**Comment by rajauser** [comment]
Already , it has been added to the buffer at 24 line. 
util.js
31:  last = d
34:  last = d.slice(end)
