### ISSUE TITLE
Erro at mega() in crypto in Node.js 11.15.0

### ISSUE THREAD

**Issue by rzorzal** [tonistiigi/mega#41]
```javascript
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 9. Received 12
    at boundsError (internal/buffer.js:50:9)
    at Buffer.readInt32BE (internal/buffer.js:370:5)
    at Object.exports.prepareKey (/home/ricardo/Repositorios/cesta/scripts/node_modules/mega/lib/crypto/index.js:35:24)
    at new Storage (/home/ricardo/Repositorios/cesta/scripts/node_modules/mega/lib/storage.js:75:21)
    at mega (/home/ricardo/Repositorios/cesta/scripts/node_modules/mega/lib/mega.js:9:10)
    at Promise (/home/ricardo/Repositorios/cesta/scripts/utils/mega-upload.js:7:29)
    at new Promise (<anonymous>)
    at Function.execute (/home/ricardo/Repositorios/cesta/scripts/utils/mega-upload.js:6:16)
    at uploadFile (/home/ricardo/Repositorios/cesta/scripts/backup/index.js:65:39)
    at init (/home/ricardo/Repositorios/cesta/scripts/backup/index.js:105:15)
```

```javascript
let mega = require('mega');
const storage = mega({email: "MY EMAIL" , password: 'MY PASSWORD', autoload:false}, function(err) {
});
```

Dont matter what account I using, this erro always appear.

Can anyone help me with this ? And also, if you have other lib to upload a file to Mega, I will be glad too

**Comment by habeelmazhar** [comment]
same issue

**Comment by rzorzal** [comment]
I changed the module to megajs, as you can see at https://www.npmjs.com/package/megajs
